global:
  scrape_interval: 5s # Check the server every 5 seconds

scrape_configs:
  - job_name: 'eventhive-backend'
    static_configs:
      # Docker networking allows us to use the container name 'backend'
      - targets: ['backend:5000']